apiVersion: storage.brewfs.io/v1alpha1
kind: BrewFSMount
metadata:
  name: demo-mount
spec:
  clusterRef:
    name: demo
  workloadKind: DaemonSet
  image: ghcr.io/ivanbeethoven/brewfs:latest
  imagePullPolicy: Always
  mountPath: /mnt/brewfs
  hostMountPath: /var/lib/brewfs/mounts/demo
  mountPropagation: Bidirectional
  configPath: /run/brewfs/config.yaml
  statePath: /var/lib/brewfs
  logLevel: brewfs=info
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists
