apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewfs-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
