apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests
  - cluster.yaml
  - mount.yaml

images:
  - name: ghcr.io/ivanbeethoven/brewfs-operator
    newTag: latest
